apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  ports:
  - port: 3000
  selector:
    app: todo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployments
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: docker.io/tnqv102/todo-app
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: ""
        - name: DB_NAME
          value: "todo_app"
        ports:
        - containerPort: 3000